baseURL = "/"
languageCode = "en"
title = "fp-tower blog"
paginate = 7
dynamicURL = "/"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[markup]
	defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
		[markup.goldmark.extensions]
			typographer = false
    [markup.goldmark.renderer]
      unsafe = true

