baseURL = "/"
languageCode = "en"
title = "fp-tower blog"
# change 2 to six (6) to alter pagination
paginate = 2
dynamicURL = "/"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[params]
  # signup for an account on formcarry.com or getform.io and replace the endpoint below
  formActionURL = "https://formcarry.com/s/3L7zY4aKd8hc"
  logoURL = "https://www.fp-tower.com/"
  twitter = "@fptower"
  logo = "logo.png"
  author = "Julien Traffaut"
  # fill in your site baseurl here ... e.g yourdomain.com
  url = "https://blog.fp-tower.com/" 

[markup]
	defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
		[markup.goldmark.extensions]
			typographer = false
    [markup.goldmark.renderer]
      unsafe = true

