baseURL = "/"
languageCode = "en"
title = "fp-tower blog"
# change 2 to six (6) to alter pagination
paginate = 2
dynamicURL = "/"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

[markup]
	defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
		[markup.goldmark.extensions]
			typographer = false
    [markup.goldmark.renderer]
      unsafe = true

